[package]
name = "s-string"
description = "s!() macro for quick String::from()"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/adam-gaia/s-string"
repository = "https://github.com/adam-gaia/s-string"

[dependencies]
